### ISSUE TITLE
数据库连接错误

### ISSUE THREAD

**Issue by leavky** [Bingjian-Zhu/gin-vue-admin#2]
您好，我在配置文件中配置了mysql 的地址，但是程序却无法连接，查看发现数据库的连接地址不对
![image](https://user-images.githubusercontent.com/46547390/80012683-473e9780-8500-11ea-9cbc-4a6fba2c6b95.png)

**Comment by Bingjian-Zhu** [comment]
@leavky 我GitHub上配的是`127.0.0.1:3306`，至于为什么你下载后变了，这问题我解析不了
```
database:
  type: mysql
  user: gin
  password: Gin123
  host: 127.0.0.1:3306
  name: gin-vue
  table-prefix: go_
```
